# Generated by Django 5.2.2 on 2025-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(blank=True, to='app.subject'),
        ),
    ]
