# Generated by Django 5.2.2 on 2025-06-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_subject_student_name_student_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='subject',
            new_name='subj',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject',
            new_name='subj',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='subj',
        ),
    ]
