# Generated by Django 5.2.2 on 2025-06-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_subject_grade_subj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subj',
        ),
    ]
