# Generated by Django 5.2.2 on 2025-06-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_subj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='student_name',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_choices',
            field=models.CharField(choices=[('Activity', 'Activity'), ('Quiz', 'Quiz'), ('Exam', 'Exam')], max_length=10),
        ),
    ]
