# Generated by Django 5.2.2 on 2025-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_student_name_grade_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
